-- Aggregates DQ failures into reject summaries and logs final metrics
-- Co-authored with CoCo
USE DATABASE P360_DQ;
USE SCHEMA AUDIT;

CREATE OR REPLACE PROCEDURE AUDIT.SP_AUDIT_REJECT_SUMMARY(
    P_RUN_ID VARCHAR, P_MODE VARCHAR DEFAULT 'INCREMENTAL'
)
RETURNS VARIANT
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
DECLARE
    v_step_run_id VARCHAR;
    v_err_msg VARCHAR;
BEGIN
    v_step_run_id := UUID_STRING();
    CALL P360_DQ.CONFIG.SP_LOG_STEP_START(:v_step_run_id, :P_RUN_ID, 60, 'AUDIT_REJECT_SUMMARY', 'AUDIT', 1);

    INSERT INTO P360_DQ.REJECT.REJECT_SUMMARY (SUMMARY_ID, RUN_ID, STEP_NAME, SOURCE_TABLE, REJECT_REASON, REJECT_COUNT, FIRST_REJECTED_AT, LAST_REJECTED_AT)
    SELECT
        UUID_STRING(), :P_RUN_ID, 'DQ_CHECK', TABLE_NM,
        'RULE_' || RULE_ID::VARCHAR || '_FEED_' || FEED_ID::VARCHAR,
        COUNT(*), MIN(RECORD_INS_TS), MAX(RECORD_INS_TS)
    FROM P360_DQ.AUDIT.DQ_RESULT
    WHERE RESULT = 'FAIL'
    GROUP BY TABLE_NM, RULE_ID, FEED_ID;

    CALL P360_DQ.CONFIG.SP_LOG_STEP_END(:v_step_run_id, 'COMPLETED', 0, 0, 0, 0, NULL, NULL, NULL);
    CALL P360_DQ.CONFIG.SP_SEND_NOTIFICATION(:P_RUN_ID, 'RUN_COMPLETE', NULL);
    RETURN OBJECT_CONSTRUCT('status', 'COMPLETED');
EXCEPTION
    WHEN OTHER THEN
        LET v_err_msg := SQLERRM;
        CALL P360_DQ.CONFIG.SP_LOG_ERROR(:P_RUN_ID, :v_step_run_id, 'AUDIT_REJECT_SUMMARY', '', '', :v_err_msg, NULL, 'ERROR');
        CALL P360_DQ.CONFIG.SP_LOG_STEP_END(:v_step_run_id, 'FAILED', 0, 0, 0, 0, :v_err_msg, '', NULL);
        RETURN OBJECT_CONSTRUCT('status', 'FAILED', 'error', :v_err_msg);
END;
$$;
